### PR TITLE
Double precision FP- instructions on 32-bit OR1K machines

### PR DESCRIPTION
**Pull request by bandvig**
Even so GCC is able to emit double precision FP- instructions (with -mhard-float and -mdouble-float options), assembler processes such instruction incorrectly, because the current binutils port defines such instructions for 64-bit OR1K machines only. The patch corrects support for double precision FP- instructions on 32-bit OR1K machines.
To verify these modifications I rebuild NewLIB-based tool chain. Next, with this tool chain I rebuild SoftFloat test tool and verified 32- and 64- bits FPU instruction execution. The computational results were right. There are differences in flags generation, especially NaNs. However, I suspect that either SoftLoad library or my FPU doesn’t follow IEEE standard accurately. Any case these mismatches are not related to binary utils. At last I compiled Whets Stone benchmark in both 32- and 64- bits variants and got results (in terms of computed digits, but, of course different MIPS, MOPS and so on) similar to both of the variants and to results I found in Internet for other machines.

### CODE REVIEW

**Comment by stffrdhrn** [comment]
FYI, I have submitted these patches to binutils upstream for review. https://sourceware.org/ml/gdb-patches/2019-03/msg00767.html

**Comment by bandvig** [comment]
@stffrdhrn 
> FYI, I have submitted these patches to binutils upstream for review. https://sourceware.org/ml/gdb-patches/2019-03/msg00767.html

Yes, Stafford.
This my pull request is obviously obsolete. We should wait till your patches goes into upstream. If I understand correctly the only thing I could do with this pull request is just to close it.

**Comment by bandvig** [comment]
@stffrdhrn @wallento 
Btw, Stafford, you mentioned me as the author of original modifications. Should I sign copyright assignment at the FSF? I'm ready to do it if it is required, but still don't understand clearly what exactly I should do.

**Comment by stffrdhrn** [comment]
@bandvig 
Hello, you are right.  In general they say anything more than 10 lines requires copyright assignment.  I sent you a mail with some details.

**Pull request closed without merging**
