### PR TITLE
sim: remove or1ksim as we have a gdb native cgen sim now

### PR DESCRIPTION
**Pull request by stffrdhrn**
The or1k cgen sim is stable and openrisc gdb is getting
ready for submitting upstream. Here I am removing the or1ksim as
it depends external libs that would not be acceptable in the gdb patch.

### CODE REVIEW

**Comment by stffrdhrn** [comment]
FYI, this was discussed in the irc chatroom. 

http://juliusbaxter.net/openrisc-irc/%23openrisc.2016-05-30.log.html#t06:38

**Comment by olofk** [comment]
Looks good to me

**Comment by jeremybennett** [comment]
Looks good to me. You can always use Or1ksim from GDB via its RSP interface at "target remote"

**Comment by wallento** [comment]
Great, thanks!

**Pull request merged**
